### PR TITLE
Update sliding-scroll.js

### PR DESCRIPTION
**Pull request by octopus3**
添加自定义偏移值，默认0，有时候开发时定位没有达到理想的位置，因此可能需要自定义一些偏移值调整

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Thanks for the PR.
Could you please add the comment below to the existing comment section of each function that makes use of the new parameter?

`* customOffset: an additional offset value to adjust the scroll position; default is 0 (no additional offset)`

**Comment by octopus3** [comment]
改好了，合并前README可能也要对应修改下咯

**Comment by Robbendebiene** [comment]
@octopus3 Good point, can you also add the new parameter there?

**Comment by octopus3** [comment]
OK,  :) 👍

**Comment by Robbendebiene** [comment]
Thank you 🙂

**Pull request merged**
